apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${PROJECT_NAME}-api
  namespace: ${ENVIRONMENT}
  labels:
    app: ${PROJECT_NAME}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${PROJECT_NAME}-api
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}-api
    spec:
      containers:
      - name: api
        image: jesusmonda/api:${ENVIRONMENT}-${CODEBUILD_BUILD_NUMBER}
        env:
        - name: NODE_ENV
          value: ${NODE_ENV}
        - name: APP_NAME
          value: ${APP_NAME}
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ${PROJECT_NAME}-api
  namespace: ${ENVIRONMENT}
spec:
  selector:
    app: ${PROJECT_NAME}-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000